FROM apache/spark:3.5.1

USER root

RUN set -eux; \
  apt-get update; \
  apt-get install -y --no-install-recommends \
    curl ca-certificates gnupg \
    build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev \
    libssl-dev libreadline-dev libffi-dev libsqlite3-dev libbz2-dev; \
  rm -rf /var/lib/apt/lists/*

RUN set -eux; \
  curl -O https://www.python.org/ftp/python/3.12.2/Python-3.12.2.tgz; \
  tar -xvf Python-3.12.2.tgz; \
  cd Python-3.12.2; \
  ./configure --enable-optimizations; \
  make -j$(nproc); \
  make altinstall; \
  cd ..; \
  rm -rf Python-3.12.2 Python-3.12.2.tgz; \
  ln -s /usr/local/bin/python3.12 /usr/bin/python3.12

RUN set -eux; \
  curl -sS https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py; \
  python3.12 /tmp/get-pip.py; \
  rm -f /tmp/get-pip.py

RUN python3.12 -m pip install --no-cache-dir beautifulsoup4 requests pandas

RUN set -eux; \
  curl -fL --retry 5 --retry-delay 2 \
    -o /opt/spark/jars/hadoop-aws-3.3.4.jar \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar; \
  curl -fL --retry 5 --retry-delay 2 \
    -o /opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar; \
  chown spark:spark /opt/spark/jars/hadoop-aws-3.3.4.jar /opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar

ENV PYSPARK_PYTHON=/usr/bin/python3.12

USER spark